[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py
addopts = --strict-markers --strict-config -ra
testpaths = accounts chores config core schedule
filterwarnings =
    error::DeprecationWarning
    default::DeprecationWarning:debug_toolbar.*
