# Generated by Django 5.2.17 on 2026-09-07 07:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_loginattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What doing it properly involves. Optional, but it settles arguments.",
                    ),
                ),
                (
                    "cadence_unit",
                    models.CharField(
                        choices=[
                            ("DAY", "days"),
                            ("WEEK", "weeks"),
                            ("MONTH", "months"),
                        ],
                        default="WEEK",
                        max_length=8,
                    ),
                ),
                (
                    "cadence_interval",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Every N units. 2 with 'weeks' means every fortnight.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "anchor_date",
                    models.DateField(
                        help_text="The due date of the first turn. Everything else steps from here."
                    ),
                ),
                (
                    "grace_days",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Days after the due date before it counts as missed. A little slack keeps the record honest about people who did it that evening.",
                        validators=[django.core.validators.MaxValueValidator(30)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to archive. Past turns are kept; no new ones are made.",
                        verbose_name="in use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chores",
                        to="accounts.household",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "name"),
                        name="unique_chore_name_per_household",
                    )
                ],
            },
        ),
    ]
