# Generated by Django 5.2.17 on 2026-09-07 07:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import accounts.managers
import accounts.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone name. Due dates and overdue checks are evaluated in this timezone.",
                        max_length=64,
                        validators=[accounts.validators.validate_timezone],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="The name other roommates see, and the name signed in with.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Can add, edit and archive chores, and manage the roommate list.",
                        verbose_name="household admin",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck when a roommate moves out. This keeps their history intact and stops them being given new turns; it does not delete anything.",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Can sign in to the Django admin site."
                    ),
                ),
                (
                    "joined_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="When they moved in. The insert point for chore rotations.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        help_text="Every roommate belongs to a household. Left empty only for an operator superuser, who administers the deployment rather than living in it.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="accounts.household",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "display_name"),
                        name="unique_display_name_per_household",
                    )
                ],
            },
            managers=[
                ("objects", accounts.managers.MemberManager()),
            ],
        ),
    ]
