# Generated by Django 5.2.17 on 2026-09-07 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(db_index=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("succeeded", models.BooleanField(default=False)),
                (
                    "attempted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["display_name", "ip_address", "attempted_at"],
                        name="accounts_lo_display_8b62bb_idx",
                    )
                ],
            },
        ),
    ]
