# Generated by Django 5.2.17 on 2026-09-07 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chores", "0002_rotationslot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_index", models.PositiveIntegerField()),
                ("period_start", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                            ("SKIPPED_AWAY", "Skipped — away"),
                            ("SWAPPED", "Swapped"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("was_late", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        help_text="Who this turn fell to when it was generated.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="chores.chore",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who actually did it. Differs from the assignee when covering.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turns_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "swapped_with",
                    models.OneToOneField(
                        blank=True,
                        help_text="The turn this one was traded with (task 19).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="swapped_from",
                        to="schedule.turn",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "chore__name"],
                "indexes": [
                    models.Index(
                        fields=["status", "due_date"],
                        name="schedule_tu_status_7a2f79_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chore", "cycle_index"),
                        name="unique_turn_per_chore_cycle",
                    )
                ],
            },
        ),
    ]
