# Generated by Django 5.2.17 on 2026-09-07 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0002_rotationslot"),
        ("schedule", "0002_awayperiod"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="turn",
            name="unique_turn_per_chore_cycle",
        ),
        migrations.AddField(
            model_name="turn",
            name="replaces",
            field=models.OneToOneField(
                blank=True,
                help_text="The skipped turn this one took over from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_by",
                to="schedule.turn",
            ),
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SKIPPED_AWAY"), _negated=True),
                fields=("chore", "cycle_index"),
                name="unique_live_turn_per_chore_cycle",
            ),
        ),
    ]
