# Generated by Django 5.2.17 on 2026-09-07 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_member_pin_is_validated"),
        ("chores", "0002_rotationslot"),
        ("schedule", "0003_remove_turn_unique_turn_per_chore_cycle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "marked done"),
                            ("MISSED", "flagged missed"),
                            ("SKIPPED_AWAY", "skipped for an absence"),
                            ("REASSIGNED", "handed on"),
                            ("SWAPPED", "swapped"),
                        ],
                        max_length=16,
                    ),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity",
                        to="chores.chore",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="accounts.household",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity",
                        to="schedule.turn",
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["household", "-at"],
                        name="schedule_ac_househo_1ef4d4_idx",
                    )
                ],
            },
        ),
    ]
